services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
