name: Java CI/CD Pipeline with Gradle

on:
  push:
    branches:
      - main  # Запускать pipeline при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать pipeline при создании Pull Request в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Указываем версию Java (например, 11, 17)
          distribution: 'temurin'  # Используем Temurin (Adoptium)

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew  # Даем права на выполнение Gradle Wrapper

      - name: Build with Gradle
        run: ./gradlew build  # Сборка проекта с помощью Gradle

      - name: Run tests
        run: ./gradlew test  # Запуск тестов

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Зависит от успешного завершения job `build`
    if: github.ref == 'refs/heads/main'  # Запускать только для ветки main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
